apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tekton-pipeline-
  namespace: default
spec:
  entrypoint: pipeline-dag
  serviceAccountName: pipeline
  templates:
    - name: pipeline-dag
      dag:
        tasks:
          - name: apply-hi-deployer-pipeline
            template: apply-resources
            arguments:
              parameters:
                - name: url
                  value: https://raw.githubusercontent.com/rampadc/hi-deployer/main/pipeline.yaml
          - name: hi-deployer
            template: hi-deployer
            dependencies:
              - apply-hi-deployer-pipeline
              - pre
          - name: pre
            template: pre
          - name: post
            template: post
            dependencies:
              - hi-deployer
          - name: post2
            template: post2
            dependencies:
              - hi-deployer
    - name: apply-resources
      inputs:
        parameters:
          - name: url
      container:
        image: quay.io/openshift/origin-cli:latest
        command:
          - /bin/bash
        args:
          - "-c"
          - oc apply -f {{inputs.parameters.url}}
    - name: hi-deployer
      resource:
        action: create
        manifest: |
          apiVersion: tekton.dev/v1
          kind: PipelineRun
          metadata:
            generateName: hi-deployer-pr-
          spec:
            pipelineRef:
              name: hi-deployer
            params:
              - name: name
                value: deployer
        successCondition: status.conditions.0.status == True
        failureCondition: status.conditions.0.status == False
    - name: pre
      container:
        image: quay.io/openshift/origin-cli:latest
        command:
          - /bin/bash
        args:
          - "-c"
          - echo "Pre"
    - name: post
      container:
        image: quay.io/openshift/origin-cli:latest
        command:
          - /bin/bash
        args:
          - "-c"
          - echo "Post 1"
    - name: post2
      container:
        image: quay.io/openshift/origin-cli:latest
        command:
          - /bin/bash
        args:
          - "-c"
          - echo "Post 2"
